development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: devel
    pool: 5
    username: root
    password: p1lipa
    host: localhost
    socket: /var/lib/mysql/mysql.sock

test:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: test
    pool: 5
    username: root
    password: p1lipa
    host: localhost
    socket: /var/lib/mysql/mysql.sock